---
title: "STA 304 Final Report"
author: "Yijia Liu"
date: "2020/12/16"
thanks: "Code and data are available at: https://github.com/LesleyyijiaLiu/The-Variables-that-Predict-Your-Income-is-XXX.git"
abstract: |
  |  
  
  | **Keywords**: Diabets, Hospital, GLM.
output: pdf_document
---

# Introduction

Diabetes is a life long condition where your body does not produce enough insulin or your body cannot use the insulin it has effectively. It can increase the risk of high blood pressure, narrowing of the arteries (atherosclerosis), coronary artery
disease and stroke. Thus, it is important to identify the patients with worse outcomes.

In general, it is hard to measure directly. However, readmissions can provide a low cost, stable estimate. If the readmissions are none, which means the treatment is great; else if the readmissions are less than 30 days, which means the treatment may not be appropriate; else if the readmissions are more than 30 days, which means the treatment is not very good, but the reason could be the patients.

To be expanded...

# Data

The datasets can be found from Kaggle and it includes over 50 features representing patient and hospital outcomes. 

To be expanded...

# Model

## Methods section

### Constructing Regression Model

#### GLM with Binomial Response

#### Generalized Linear Mixed Models (GLMMs)

## Variable Selection

## Model Validation/ Dignostics

# Results

## Description of Data

## Process of Obtaining Final Model

## Goodness of Final Model

# Discussion

## Final Model Interpretation and Importance

## Limitations of Analysis